/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-23 at 10:15:57 UTC 
 * Modify at your own risk.
 */

package epusp.pcs.os.workflow.emcallworkflowendpoint.model;

/**
 * Model definition for Licence.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the emcallworkflowendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Licence extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String licenceType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String registerCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime validUntil;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLicenceType() {
    return licenceType;
  }

  /**
   * @param licenceType licenceType or {@code null} for none
   */
  public Licence setLicenceType(java.lang.String licenceType) {
    this.licenceType = licenceType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRegisterCode() {
    return registerCode;
  }

  /**
   * @param registerCode registerCode or {@code null} for none
   */
  public Licence setRegisterCode(java.lang.String registerCode) {
    this.registerCode = registerCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getValidUntil() {
    return validUntil;
  }

  /**
   * @param validUntil validUntil or {@code null} for none
   */
  public Licence setValidUntil(com.google.api.client.util.DateTime validUntil) {
    this.validUntil = validUntil;
    return this;
  }

  @Override
  public Licence set(String fieldName, Object value) {
    return (Licence) super.set(fieldName, value);
  }

  @Override
  public Licence clone() {
    return (Licence) super.clone();
  }

}
