/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-23 at 10:15:57 UTC 
 * Modify at your own risk.
 */

package epusp.pcs.os.workflow.emcallworkflowendpoint;

/**
 * Service definition for Emcallworkflowendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link EmcallworkflowendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Emcallworkflowendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the emcallworkflowendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://epusp-pcsos.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "emcallworkflowendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Emcallworkflowendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Emcallworkflowendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "ackVehicleFinishedCall".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link AckVehicleFinishedCall#execute()} method to invoke the
   * remote operation.
   *
   * @param vehicleId
   * @return the request
   */
  public AckVehicleFinishedCall ackVehicleFinishedCall(java.lang.String vehicleId) throws java.io.IOException {
    AckVehicleFinishedCall result = new AckVehicleFinishedCall(vehicleId);
    initialize(result);
    return result;
  }

  public class AckVehicleFinishedCall extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "ackVehicleFinishedCall/{vehicleId}";

    /**
     * Create a request for the method "ackVehicleFinishedCall".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link AckVehicleFinishedCall#execute()} method to
     * invoke the remote operation. <p> {@link AckVehicleFinishedCall#initialize(com.google.api.client
     * .googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param vehicleId
     * @since 1.13
     */
    protected AckVehicleFinishedCall(java.lang.String vehicleId) {
      super(Emcallworkflowendpoint.this, "POST", REST_PATH, null, Void.class);
      this.vehicleId = com.google.api.client.util.Preconditions.checkNotNull(vehicleId, "Required parameter vehicleId must be specified.");
    }

    @Override
    public AckVehicleFinishedCall setAlt(java.lang.String alt) {
      return (AckVehicleFinishedCall) super.setAlt(alt);
    }

    @Override
    public AckVehicleFinishedCall setFields(java.lang.String fields) {
      return (AckVehicleFinishedCall) super.setFields(fields);
    }

    @Override
    public AckVehicleFinishedCall setKey(java.lang.String key) {
      return (AckVehicleFinishedCall) super.setKey(key);
    }

    @Override
    public AckVehicleFinishedCall setOauthToken(java.lang.String oauthToken) {
      return (AckVehicleFinishedCall) super.setOauthToken(oauthToken);
    }

    @Override
    public AckVehicleFinishedCall setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AckVehicleFinishedCall) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AckVehicleFinishedCall setQuotaUser(java.lang.String quotaUser) {
      return (AckVehicleFinishedCall) super.setQuotaUser(quotaUser);
    }

    @Override
    public AckVehicleFinishedCall setUserIp(java.lang.String userIp) {
      return (AckVehicleFinishedCall) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String vehicleId;

    /**

     */
    public java.lang.String getVehicleId() {
      return vehicleId;
    }

    public AckVehicleFinishedCall setVehicleId(java.lang.String vehicleId) {
      this.vehicleId = vehicleId;
      return this;
    }

    @Override
    public AckVehicleFinishedCall set(String parameterName, Object value) {
      return (AckVehicleFinishedCall) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "ackVehicleOnCall".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link AckVehicleOnCall#execute()} method to invoke the remote
   * operation.
   *
   * @param vehicleId
   * @return the request
   */
  public AckVehicleOnCall ackVehicleOnCall(java.lang.String vehicleId) throws java.io.IOException {
    AckVehicleOnCall result = new AckVehicleOnCall(vehicleId);
    initialize(result);
    return result;
  }

  public class AckVehicleOnCall extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "ackVehicleOnCall/{vehicleId}";

    /**
     * Create a request for the method "ackVehicleOnCall".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link AckVehicleOnCall#execute()} method to invoke
     * the remote operation. <p> {@link AckVehicleOnCall#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param vehicleId
     * @since 1.13
     */
    protected AckVehicleOnCall(java.lang.String vehicleId) {
      super(Emcallworkflowendpoint.this, "POST", REST_PATH, null, Void.class);
      this.vehicleId = com.google.api.client.util.Preconditions.checkNotNull(vehicleId, "Required parameter vehicleId must be specified.");
    }

    @Override
    public AckVehicleOnCall setAlt(java.lang.String alt) {
      return (AckVehicleOnCall) super.setAlt(alt);
    }

    @Override
    public AckVehicleOnCall setFields(java.lang.String fields) {
      return (AckVehicleOnCall) super.setFields(fields);
    }

    @Override
    public AckVehicleOnCall setKey(java.lang.String key) {
      return (AckVehicleOnCall) super.setKey(key);
    }

    @Override
    public AckVehicleOnCall setOauthToken(java.lang.String oauthToken) {
      return (AckVehicleOnCall) super.setOauthToken(oauthToken);
    }

    @Override
    public AckVehicleOnCall setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AckVehicleOnCall) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AckVehicleOnCall setQuotaUser(java.lang.String quotaUser) {
      return (AckVehicleOnCall) super.setQuotaUser(quotaUser);
    }

    @Override
    public AckVehicleOnCall setUserIp(java.lang.String userIp) {
      return (AckVehicleOnCall) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String vehicleId;

    /**

     */
    public java.lang.String getVehicleId() {
      return vehicleId;
    }

    public AckVehicleOnCall setVehicleId(java.lang.String vehicleId) {
      this.vehicleId = vehicleId;
      return this;
    }

    @Override
    public AckVehicleOnCall set(String parameterName, Object value) {
      return (AckVehicleOnCall) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addAgentToVehicle".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link AddAgentToVehicle#execute()} method to invoke the remote
   * operation.
   *
   * @param vehicleId
   * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Agent}
   * @return the request
   */
  public AddAgentToVehicle addAgentToVehicle(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Agent content) throws java.io.IOException {
    AddAgentToVehicle result = new AddAgentToVehicle(vehicleId, content);
    initialize(result);
    return result;
  }

  public class AddAgentToVehicle extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "addAgentToVehicle/{vehicleId}";

    /**
     * Create a request for the method "addAgentToVehicle".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link AddAgentToVehicle#execute()} method to invoke
     * the remote operation. <p> {@link AddAgentToVehicle#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param vehicleId
     * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Agent}
     * @since 1.13
     */
    protected AddAgentToVehicle(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Agent content) {
      super(Emcallworkflowendpoint.this, "POST", REST_PATH, content, Void.class);
      this.vehicleId = com.google.api.client.util.Preconditions.checkNotNull(vehicleId, "Required parameter vehicleId must be specified.");
    }

    @Override
    public AddAgentToVehicle setAlt(java.lang.String alt) {
      return (AddAgentToVehicle) super.setAlt(alt);
    }

    @Override
    public AddAgentToVehicle setFields(java.lang.String fields) {
      return (AddAgentToVehicle) super.setFields(fields);
    }

    @Override
    public AddAgentToVehicle setKey(java.lang.String key) {
      return (AddAgentToVehicle) super.setKey(key);
    }

    @Override
    public AddAgentToVehicle setOauthToken(java.lang.String oauthToken) {
      return (AddAgentToVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public AddAgentToVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddAgentToVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddAgentToVehicle setQuotaUser(java.lang.String quotaUser) {
      return (AddAgentToVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddAgentToVehicle setUserIp(java.lang.String userIp) {
      return (AddAgentToVehicle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String vehicleId;

    /**

     */
    public java.lang.String getVehicleId() {
      return vehicleId;
    }

    public AddAgentToVehicle setVehicleId(java.lang.String vehicleId) {
      this.vehicleId = vehicleId;
      return this;
    }

    @Override
    public AddAgentToVehicle set(String parameterName, Object value) {
      return (AddAgentToVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addAgentsToVehicle".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link AddAgentsToVehicle#execute()} method to invoke the remote
   * operation.
   *
   * @param vehicleId
   * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.AgentCollection}
   * @return the request
   */
  public AddAgentsToVehicle addAgentsToVehicle(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.AgentCollection content) throws java.io.IOException {
    AddAgentsToVehicle result = new AddAgentsToVehicle(vehicleId, content);
    initialize(result);
    return result;
  }

  public class AddAgentsToVehicle extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "addAgentsToVehicle/{vehicleId}";

    /**
     * Create a request for the method "addAgentsToVehicle".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link AddAgentsToVehicle#execute()} method to invoke
     * the remote operation. <p> {@link AddAgentsToVehicle#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param vehicleId
     * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.AgentCollection}
     * @since 1.13
     */
    protected AddAgentsToVehicle(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.AgentCollection content) {
      super(Emcallworkflowendpoint.this, "POST", REST_PATH, content, Void.class);
      this.vehicleId = com.google.api.client.util.Preconditions.checkNotNull(vehicleId, "Required parameter vehicleId must be specified.");
    }

    @Override
    public AddAgentsToVehicle setAlt(java.lang.String alt) {
      return (AddAgentsToVehicle) super.setAlt(alt);
    }

    @Override
    public AddAgentsToVehicle setFields(java.lang.String fields) {
      return (AddAgentsToVehicle) super.setFields(fields);
    }

    @Override
    public AddAgentsToVehicle setKey(java.lang.String key) {
      return (AddAgentsToVehicle) super.setKey(key);
    }

    @Override
    public AddAgentsToVehicle setOauthToken(java.lang.String oauthToken) {
      return (AddAgentsToVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public AddAgentsToVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddAgentsToVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddAgentsToVehicle setQuotaUser(java.lang.String quotaUser) {
      return (AddAgentsToVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddAgentsToVehicle setUserIp(java.lang.String userIp) {
      return (AddAgentsToVehicle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String vehicleId;

    /**

     */
    public java.lang.String getVehicleId() {
      return vehicleId;
    }

    public AddAgentsToVehicle setVehicleId(java.lang.String vehicleId) {
      this.vehicleId = vehicleId;
      return this;
    }

    @Override
    public AddAgentsToVehicle set(String parameterName, Object value) {
      return (AddAgentsToVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addFreeVehicle".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link AddFreeVehicle#execute()} method to invoke the remote
   * operation.
   *
   * @param vehicleId
   * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.AgentCollection}
   * @return the request
   */
  public AddFreeVehicle addFreeVehicle(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.AgentCollection content) throws java.io.IOException {
    AddFreeVehicle result = new AddFreeVehicle(vehicleId, content);
    initialize(result);
    return result;
  }

  public class AddFreeVehicle extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "addFreeVehicle/{vehicleId}";

    /**
     * Create a request for the method "addFreeVehicle".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link AddFreeVehicle#execute()} method to invoke the
     * remote operation. <p> {@link AddFreeVehicle#initialize(com.google.api.client.googleapis.service
     * s.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param vehicleId
     * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.AgentCollection}
     * @since 1.13
     */
    protected AddFreeVehicle(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.AgentCollection content) {
      super(Emcallworkflowendpoint.this, "POST", REST_PATH, content, Void.class);
      this.vehicleId = com.google.api.client.util.Preconditions.checkNotNull(vehicleId, "Required parameter vehicleId must be specified.");
    }

    @Override
    public AddFreeVehicle setAlt(java.lang.String alt) {
      return (AddFreeVehicle) super.setAlt(alt);
    }

    @Override
    public AddFreeVehicle setFields(java.lang.String fields) {
      return (AddFreeVehicle) super.setFields(fields);
    }

    @Override
    public AddFreeVehicle setKey(java.lang.String key) {
      return (AddFreeVehicle) super.setKey(key);
    }

    @Override
    public AddFreeVehicle setOauthToken(java.lang.String oauthToken) {
      return (AddFreeVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public AddFreeVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddFreeVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddFreeVehicle setQuotaUser(java.lang.String quotaUser) {
      return (AddFreeVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddFreeVehicle setUserIp(java.lang.String userIp) {
      return (AddFreeVehicle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String vehicleId;

    /**

     */
    public java.lang.String getVehicleId() {
      return vehicleId;
    }

    public AddFreeVehicle setVehicleId(java.lang.String vehicleId) {
      this.vehicleId = vehicleId;
      return this;
    }

    @Override
    public AddFreeVehicle set(String parameterName, Object value) {
      return (AddFreeVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addVictimPosition".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link AddVictimPosition#execute()} method to invoke the remote
   * operation.
   *
   * @param victimEmail
   * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position}
   * @return the request
   */
  public AddVictimPosition addVictimPosition(java.lang.String victimEmail, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position content) throws java.io.IOException {
    AddVictimPosition result = new AddVictimPosition(victimEmail, content);
    initialize(result);
    return result;
  }

  public class AddVictimPosition extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "addVictimPosition/{victimEmail}";

    /**
     * Create a request for the method "addVictimPosition".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link AddVictimPosition#execute()} method to invoke
     * the remote operation. <p> {@link AddVictimPosition#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param victimEmail
     * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position}
     * @since 1.13
     */
    protected AddVictimPosition(java.lang.String victimEmail, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position content) {
      super(Emcallworkflowendpoint.this, "POST", REST_PATH, content, Void.class);
      this.victimEmail = com.google.api.client.util.Preconditions.checkNotNull(victimEmail, "Required parameter victimEmail must be specified.");
    }

    @Override
    public AddVictimPosition setAlt(java.lang.String alt) {
      return (AddVictimPosition) super.setAlt(alt);
    }

    @Override
    public AddVictimPosition setFields(java.lang.String fields) {
      return (AddVictimPosition) super.setFields(fields);
    }

    @Override
    public AddVictimPosition setKey(java.lang.String key) {
      return (AddVictimPosition) super.setKey(key);
    }

    @Override
    public AddVictimPosition setOauthToken(java.lang.String oauthToken) {
      return (AddVictimPosition) super.setOauthToken(oauthToken);
    }

    @Override
    public AddVictimPosition setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddVictimPosition) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddVictimPosition setQuotaUser(java.lang.String quotaUser) {
      return (AddVictimPosition) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddVictimPosition setUserIp(java.lang.String userIp) {
      return (AddVictimPosition) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String victimEmail;

    /**

     */
    public java.lang.String getVictimEmail() {
      return victimEmail;
    }

    public AddVictimPosition setVictimEmail(java.lang.String victimEmail) {
      this.victimEmail = victimEmail;
      return this;
    }

    @Override
    public AddVictimPosition set(String parameterName, Object value) {
      return (AddVictimPosition) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addWaitingCall".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link AddWaitingCall#execute()} method to invoke the remote
   * operation.
   *
   * @param victimEmail
   * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position}
   * @return the request
   */
  public AddWaitingCall addWaitingCall(java.lang.String victimEmail, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position content) throws java.io.IOException {
    AddWaitingCall result = new AddWaitingCall(victimEmail, content);
    initialize(result);
    return result;
  }

  public class AddWaitingCall extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "addWaitingCall/{victimEmail}";

    /**
     * Create a request for the method "addWaitingCall".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link AddWaitingCall#execute()} method to invoke the
     * remote operation. <p> {@link AddWaitingCall#initialize(com.google.api.client.googleapis.service
     * s.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param victimEmail
     * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position}
     * @since 1.13
     */
    protected AddWaitingCall(java.lang.String victimEmail, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position content) {
      super(Emcallworkflowendpoint.this, "POST", REST_PATH, content, Void.class);
      this.victimEmail = com.google.api.client.util.Preconditions.checkNotNull(victimEmail, "Required parameter victimEmail must be specified.");
    }

    @Override
    public AddWaitingCall setAlt(java.lang.String alt) {
      return (AddWaitingCall) super.setAlt(alt);
    }

    @Override
    public AddWaitingCall setFields(java.lang.String fields) {
      return (AddWaitingCall) super.setFields(fields);
    }

    @Override
    public AddWaitingCall setKey(java.lang.String key) {
      return (AddWaitingCall) super.setKey(key);
    }

    @Override
    public AddWaitingCall setOauthToken(java.lang.String oauthToken) {
      return (AddWaitingCall) super.setOauthToken(oauthToken);
    }

    @Override
    public AddWaitingCall setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddWaitingCall) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddWaitingCall setQuotaUser(java.lang.String quotaUser) {
      return (AddWaitingCall) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddWaitingCall setUserIp(java.lang.String userIp) {
      return (AddWaitingCall) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String victimEmail;

    /**

     */
    public java.lang.String getVictimEmail() {
      return victimEmail;
    }

    public AddWaitingCall setVictimEmail(java.lang.String victimEmail) {
      this.victimEmail = victimEmail;
      return this;
    }

    @Override
    public AddWaitingCall set(String parameterName, Object value) {
      return (AddWaitingCall) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAgentFromVehicle".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAgentFromVehicle#execute()} method to invoke the
   * remote operation.
   *
   * @param vehicleId
   * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Agent}
   * @return the request
   */
  public RemoveAgentFromVehicle removeAgentFromVehicle(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Agent content) throws java.io.IOException {
    RemoveAgentFromVehicle result = new RemoveAgentFromVehicle(vehicleId, content);
    initialize(result);
    return result;
  }

  public class RemoveAgentFromVehicle extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "agentfromvehicle/{vehicleId}";

    /**
     * Create a request for the method "removeAgentFromVehicle".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link RemoveAgentFromVehicle#execute()} method to
     * invoke the remote operation. <p> {@link RemoveAgentFromVehicle#initialize(com.google.api.client
     * .googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param vehicleId
     * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Agent}
     * @since 1.13
     */
    protected RemoveAgentFromVehicle(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Agent content) {
      super(Emcallworkflowendpoint.this, "DELETE", REST_PATH, content, Void.class);
      this.vehicleId = com.google.api.client.util.Preconditions.checkNotNull(vehicleId, "Required parameter vehicleId must be specified.");
    }

    @Override
    public RemoveAgentFromVehicle setAlt(java.lang.String alt) {
      return (RemoveAgentFromVehicle) super.setAlt(alt);
    }

    @Override
    public RemoveAgentFromVehicle setFields(java.lang.String fields) {
      return (RemoveAgentFromVehicle) super.setFields(fields);
    }

    @Override
    public RemoveAgentFromVehicle setKey(java.lang.String key) {
      return (RemoveAgentFromVehicle) super.setKey(key);
    }

    @Override
    public RemoveAgentFromVehicle setOauthToken(java.lang.String oauthToken) {
      return (RemoveAgentFromVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAgentFromVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAgentFromVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAgentFromVehicle setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAgentFromVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAgentFromVehicle setUserIp(java.lang.String userIp) {
      return (RemoveAgentFromVehicle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String vehicleId;

    /**

     */
    public java.lang.String getVehicleId() {
      return vehicleId;
    }

    public RemoveAgentFromVehicle setVehicleId(java.lang.String vehicleId) {
      this.vehicleId = vehicleId;
      return this;
    }

    @Override
    public RemoveAgentFromVehicle set(String parameterName, Object value) {
      return (RemoveAgentFromVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAllAgentsFromVehicle".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAllAgentsFromVehicle#execute()} method to invoke the
   * remote operation.
   *
   * @param vehicleId
   * @return the request
   */
  public RemoveAllAgentsFromVehicle removeAllAgentsFromVehicle(java.lang.String vehicleId) throws java.io.IOException {
    RemoveAllAgentsFromVehicle result = new RemoveAllAgentsFromVehicle(vehicleId);
    initialize(result);
    return result;
  }

  public class RemoveAllAgentsFromVehicle extends EmcallworkflowendpointRequest<Void> {

    private static final String REST_PATH = "allagentsfromvehicle/{vehicleId}";

    /**
     * Create a request for the method "removeAllAgentsFromVehicle".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link RemoveAllAgentsFromVehicle#execute()} method
     * to invoke the remote operation. <p> {@link RemoveAllAgentsFromVehicle#initialize(com.google.api
     * .client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @param vehicleId
     * @since 1.13
     */
    protected RemoveAllAgentsFromVehicle(java.lang.String vehicleId) {
      super(Emcallworkflowendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.vehicleId = com.google.api.client.util.Preconditions.checkNotNull(vehicleId, "Required parameter vehicleId must be specified.");
    }

    @Override
    public RemoveAllAgentsFromVehicle setAlt(java.lang.String alt) {
      return (RemoveAllAgentsFromVehicle) super.setAlt(alt);
    }

    @Override
    public RemoveAllAgentsFromVehicle setFields(java.lang.String fields) {
      return (RemoveAllAgentsFromVehicle) super.setFields(fields);
    }

    @Override
    public RemoveAllAgentsFromVehicle setKey(java.lang.String key) {
      return (RemoveAllAgentsFromVehicle) super.setKey(key);
    }

    @Override
    public RemoveAllAgentsFromVehicle setOauthToken(java.lang.String oauthToken) {
      return (RemoveAllAgentsFromVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAllAgentsFromVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAllAgentsFromVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAllAgentsFromVehicle setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAllAgentsFromVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAllAgentsFromVehicle setUserIp(java.lang.String userIp) {
      return (RemoveAllAgentsFromVehicle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String vehicleId;

    /**

     */
    public java.lang.String getVehicleId() {
      return vehicleId;
    }

    public RemoveAllAgentsFromVehicle setVehicleId(java.lang.String vehicleId) {
      this.vehicleId = vehicleId;
      return this;
    }

    @Override
    public RemoveAllAgentsFromVehicle set(String parameterName, Object value) {
      return (RemoveAllAgentsFromVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePositionAndVerifyStatus".
   *
   * This request holds the parameters needed by the emcallworkflowendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePositionAndVerifyStatus#execute()} method to invoke
   * the remote operation.
   *
   * @param vehicleId
   * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position}
   * @return the request
   */
  public UpdatePositionAndVerifyStatus updatePositionAndVerifyStatus(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position content) throws java.io.IOException {
    UpdatePositionAndVerifyStatus result = new UpdatePositionAndVerifyStatus(vehicleId, content);
    initialize(result);
    return result;
  }

  public class UpdatePositionAndVerifyStatus extends EmcallworkflowendpointRequest<epusp.pcs.os.workflow.emcallworkflowendpoint.model.EmergencyCall> {

    private static final String REST_PATH = "emergencycall/{vehicleId}";

    /**
     * Create a request for the method "updatePositionAndVerifyStatus".
     *
     * This request holds the parameters needed by the the emcallworkflowendpoint server.  After
     * setting any optional parameters, call the {@link UpdatePositionAndVerifyStatus#execute()}
     * method to invoke the remote operation. <p> {@link UpdatePositionAndVerifyStatus#initialize(com.
     * google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be called to
     * initialize this instance immediately after invoking the constructor. </p>
     *
     * @param vehicleId
     * @param content the {@link epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position}
     * @since 1.13
     */
    protected UpdatePositionAndVerifyStatus(java.lang.String vehicleId, epusp.pcs.os.workflow.emcallworkflowendpoint.model.Position content) {
      super(Emcallworkflowendpoint.this, "PUT", REST_PATH, content, epusp.pcs.os.workflow.emcallworkflowendpoint.model.EmergencyCall.class);
      this.vehicleId = com.google.api.client.util.Preconditions.checkNotNull(vehicleId, "Required parameter vehicleId must be specified.");
    }

    @Override
    public UpdatePositionAndVerifyStatus setAlt(java.lang.String alt) {
      return (UpdatePositionAndVerifyStatus) super.setAlt(alt);
    }

    @Override
    public UpdatePositionAndVerifyStatus setFields(java.lang.String fields) {
      return (UpdatePositionAndVerifyStatus) super.setFields(fields);
    }

    @Override
    public UpdatePositionAndVerifyStatus setKey(java.lang.String key) {
      return (UpdatePositionAndVerifyStatus) super.setKey(key);
    }

    @Override
    public UpdatePositionAndVerifyStatus setOauthToken(java.lang.String oauthToken) {
      return (UpdatePositionAndVerifyStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePositionAndVerifyStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePositionAndVerifyStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePositionAndVerifyStatus setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePositionAndVerifyStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePositionAndVerifyStatus setUserIp(java.lang.String userIp) {
      return (UpdatePositionAndVerifyStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String vehicleId;

    /**

     */
    public java.lang.String getVehicleId() {
      return vehicleId;
    }

    public UpdatePositionAndVerifyStatus setVehicleId(java.lang.String vehicleId) {
      this.vehicleId = vehicleId;
      return this;
    }

    @Override
    public UpdatePositionAndVerifyStatus set(String parameterName, Object value) {
      return (UpdatePositionAndVerifyStatus) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Emcallworkflowendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Emcallworkflowendpoint}. */
    @Override
    public Emcallworkflowendpoint build() {
      return new Emcallworkflowendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link EmcallworkflowendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setEmcallworkflowendpointRequestInitializer(
        EmcallworkflowendpointRequestInitializer emcallworkflowendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(emcallworkflowendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
