/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-21 at 03:14:39 UTC 
 * Modify at your own risk.
 */

package com.pcsos.backend.shared.dispositivoendpoint;

/**
 * Service definition for Dispositivoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link DispositivoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Dispositivoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the dispositivoendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://csce470-rottenpotatoes.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "dispositivoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Dispositivoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Dispositivoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getDispositivo".
   *
   * This request holds the parameters needed by the dispositivoendpoint server.  After setting any
   * optional parameters, call the {@link GetDispositivo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetDispositivo getDispositivo(java.lang.Long id) throws java.io.IOException {
    GetDispositivo result = new GetDispositivo(id);
    initialize(result);
    return result;
  }

  public class GetDispositivo extends DispositivoendpointRequest<com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo> {

    private static final String REST_PATH = "dispositivo/{id}";

    /**
     * Create a request for the method "getDispositivo".
     *
     * This request holds the parameters needed by the the dispositivoendpoint server.  After setting
     * any optional parameters, call the {@link GetDispositivo#execute()} method to invoke the remote
     * operation. <p> {@link GetDispositivo#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetDispositivo(java.lang.Long id) {
      super(Dispositivoendpoint.this, "GET", REST_PATH, null, com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetDispositivo setAlt(java.lang.String alt) {
      return (GetDispositivo) super.setAlt(alt);
    }

    @Override
    public GetDispositivo setFields(java.lang.String fields) {
      return (GetDispositivo) super.setFields(fields);
    }

    @Override
    public GetDispositivo setKey(java.lang.String key) {
      return (GetDispositivo) super.setKey(key);
    }

    @Override
    public GetDispositivo setOauthToken(java.lang.String oauthToken) {
      return (GetDispositivo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetDispositivo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetDispositivo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetDispositivo setQuotaUser(java.lang.String quotaUser) {
      return (GetDispositivo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetDispositivo setUserIp(java.lang.String userIp) {
      return (GetDispositivo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetDispositivo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetDispositivo set(String parameterName, Object value) {
      return (GetDispositivo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertDispositivo".
   *
   * This request holds the parameters needed by the dispositivoendpoint server.  After setting any
   * optional parameters, call the {@link InsertDispositivo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo}
   * @return the request
   */
  public InsertDispositivo insertDispositivo(com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo content) throws java.io.IOException {
    InsertDispositivo result = new InsertDispositivo(content);
    initialize(result);
    return result;
  }

  public class InsertDispositivo extends DispositivoendpointRequest<com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo> {

    private static final String REST_PATH = "dispositivo";

    /**
     * Create a request for the method "insertDispositivo".
     *
     * This request holds the parameters needed by the the dispositivoendpoint server.  After setting
     * any optional parameters, call the {@link InsertDispositivo#execute()} method to invoke the
     * remote operation. <p> {@link InsertDispositivo#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo}
     * @since 1.13
     */
    protected InsertDispositivo(com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo content) {
      super(Dispositivoendpoint.this, "POST", REST_PATH, content, com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo.class);
    }

    @Override
    public InsertDispositivo setAlt(java.lang.String alt) {
      return (InsertDispositivo) super.setAlt(alt);
    }

    @Override
    public InsertDispositivo setFields(java.lang.String fields) {
      return (InsertDispositivo) super.setFields(fields);
    }

    @Override
    public InsertDispositivo setKey(java.lang.String key) {
      return (InsertDispositivo) super.setKey(key);
    }

    @Override
    public InsertDispositivo setOauthToken(java.lang.String oauthToken) {
      return (InsertDispositivo) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertDispositivo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertDispositivo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertDispositivo setQuotaUser(java.lang.String quotaUser) {
      return (InsertDispositivo) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertDispositivo setUserIp(java.lang.String userIp) {
      return (InsertDispositivo) super.setUserIp(userIp);
    }

    @Override
    public InsertDispositivo set(String parameterName, Object value) {
      return (InsertDispositivo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listDispositivo".
   *
   * This request holds the parameters needed by the dispositivoendpoint server.  After setting any
   * optional parameters, call the {@link ListDispositivo#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListDispositivo listDispositivo() throws java.io.IOException {
    ListDispositivo result = new ListDispositivo();
    initialize(result);
    return result;
  }

  public class ListDispositivo extends DispositivoendpointRequest<com.pcsos.backend.shared.dispositivoendpoint.model.CollectionResponseDispositivo> {

    private static final String REST_PATH = "dispositivo";

    /**
     * Create a request for the method "listDispositivo".
     *
     * This request holds the parameters needed by the the dispositivoendpoint server.  After setting
     * any optional parameters, call the {@link ListDispositivo#execute()} method to invoke the remote
     * operation. <p> {@link ListDispositivo#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListDispositivo() {
      super(Dispositivoendpoint.this, "GET", REST_PATH, null, com.pcsos.backend.shared.dispositivoendpoint.model.CollectionResponseDispositivo.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListDispositivo setAlt(java.lang.String alt) {
      return (ListDispositivo) super.setAlt(alt);
    }

    @Override
    public ListDispositivo setFields(java.lang.String fields) {
      return (ListDispositivo) super.setFields(fields);
    }

    @Override
    public ListDispositivo setKey(java.lang.String key) {
      return (ListDispositivo) super.setKey(key);
    }

    @Override
    public ListDispositivo setOauthToken(java.lang.String oauthToken) {
      return (ListDispositivo) super.setOauthToken(oauthToken);
    }

    @Override
    public ListDispositivo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListDispositivo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListDispositivo setQuotaUser(java.lang.String quotaUser) {
      return (ListDispositivo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListDispositivo setUserIp(java.lang.String userIp) {
      return (ListDispositivo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListDispositivo setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListDispositivo setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListDispositivo set(String parameterName, Object value) {
      return (ListDispositivo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeDispositivo".
   *
   * This request holds the parameters needed by the dispositivoendpoint server.  After setting any
   * optional parameters, call the {@link RemoveDispositivo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveDispositivo removeDispositivo(java.lang.Long id) throws java.io.IOException {
    RemoveDispositivo result = new RemoveDispositivo(id);
    initialize(result);
    return result;
  }

  public class RemoveDispositivo extends DispositivoendpointRequest<Void> {

    private static final String REST_PATH = "dispositivo/{id}";

    /**
     * Create a request for the method "removeDispositivo".
     *
     * This request holds the parameters needed by the the dispositivoendpoint server.  After setting
     * any optional parameters, call the {@link RemoveDispositivo#execute()} method to invoke the
     * remote operation. <p> {@link RemoveDispositivo#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveDispositivo(java.lang.Long id) {
      super(Dispositivoendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveDispositivo setAlt(java.lang.String alt) {
      return (RemoveDispositivo) super.setAlt(alt);
    }

    @Override
    public RemoveDispositivo setFields(java.lang.String fields) {
      return (RemoveDispositivo) super.setFields(fields);
    }

    @Override
    public RemoveDispositivo setKey(java.lang.String key) {
      return (RemoveDispositivo) super.setKey(key);
    }

    @Override
    public RemoveDispositivo setOauthToken(java.lang.String oauthToken) {
      return (RemoveDispositivo) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveDispositivo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveDispositivo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveDispositivo setQuotaUser(java.lang.String quotaUser) {
      return (RemoveDispositivo) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveDispositivo setUserIp(java.lang.String userIp) {
      return (RemoveDispositivo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveDispositivo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveDispositivo set(String parameterName, Object value) {
      return (RemoveDispositivo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateDispositivo".
   *
   * This request holds the parameters needed by the dispositivoendpoint server.  After setting any
   * optional parameters, call the {@link UpdateDispositivo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo}
   * @return the request
   */
  public UpdateDispositivo updateDispositivo(com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo content) throws java.io.IOException {
    UpdateDispositivo result = new UpdateDispositivo(content);
    initialize(result);
    return result;
  }

  public class UpdateDispositivo extends DispositivoendpointRequest<com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo> {

    private static final String REST_PATH = "dispositivo";

    /**
     * Create a request for the method "updateDispositivo".
     *
     * This request holds the parameters needed by the the dispositivoendpoint server.  After setting
     * any optional parameters, call the {@link UpdateDispositivo#execute()} method to invoke the
     * remote operation. <p> {@link UpdateDispositivo#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo}
     * @since 1.13
     */
    protected UpdateDispositivo(com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo content) {
      super(Dispositivoendpoint.this, "PUT", REST_PATH, content, com.pcsos.backend.shared.dispositivoendpoint.model.Dispositivo.class);
    }

    @Override
    public UpdateDispositivo setAlt(java.lang.String alt) {
      return (UpdateDispositivo) super.setAlt(alt);
    }

    @Override
    public UpdateDispositivo setFields(java.lang.String fields) {
      return (UpdateDispositivo) super.setFields(fields);
    }

    @Override
    public UpdateDispositivo setKey(java.lang.String key) {
      return (UpdateDispositivo) super.setKey(key);
    }

    @Override
    public UpdateDispositivo setOauthToken(java.lang.String oauthToken) {
      return (UpdateDispositivo) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateDispositivo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateDispositivo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateDispositivo setQuotaUser(java.lang.String quotaUser) {
      return (UpdateDispositivo) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateDispositivo setUserIp(java.lang.String userIp) {
      return (UpdateDispositivo) super.setUserIp(userIp);
    }

    @Override
    public UpdateDispositivo set(String parameterName, Object value) {
      return (UpdateDispositivo) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Dispositivoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Dispositivoendpoint}. */
    @Override
    public Dispositivoendpoint build() {
      return new Dispositivoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link DispositivoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setDispositivoendpointRequestInitializer(
        DispositivoendpointRequestInitializer dispositivoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(dispositivoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
